#%RAML 1.0
title: CodeEtch API
version: v1
baseUri: http://api.codeEtch.com
types:
  Url: string
  User:
    type: object
    properties:

  Repository:
    type: object
    properties:
      repoUrl: Url
      name: string
      owner: User

/repositories:
  post:
    description: Create a new repository on the server
    body:
      application/json:
        type:
          Url
        example:
          "https://github.com/CodeEtch/backend.git"
  /{repository_id}/packages:
    get:
      description: Get all the packages in the repository

/packages:
  /{package_id}:
    get:

/classes:
  /{class_id}:
    get:
    /attributes:
      get:
    /methods:
      get:

/relationships:
  /repositories/{repository_id}:
    get:
  /packages/{package_id}:
    get:
  /classes/{class_id}:
    get:
